# Plex Configuration File

server:
  name: "Plexus"
  motd: "%servername% - Minecraft %mcversion%"
  colorize_motd: true

# Ban message is customized here. Additional messages can be configured in messages.yml
banning:
  message: "&cYou are banned! Please appeal on the forums at https://forum.plex.us.org/"


# Settings for commands relating to Plex
commands:
  # Should Plex use a "true op" system with ranks or only permission nodes
  permissions: ranks

data:
  central:
    storage: sqlite # Use mariadb, mongodb, or sqlite here
    user: ""
    password: ""
    hostname: 127.0.0.1
    port: 27017
    db: "plex"
  side: # This is Redis, leave password blank if auth is false
    auth: true
    hostname: 127.0.0.1
    port: 6379
    password: ""

worlds:
  flatlands:
    name: "Flatlands"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1
  adminworld:
    name: "Admin World"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1
  masterbuilderworld:
    name: "MasterBuilder World"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1

# Additional logging for debugging
debug: false